---
funtional:
  - Пользователь должен иметь возможность создать учетную запись
  - Пользователь должен иметь возможность авторизоваться под созданной учетной записью
  - Пользователь должен иметь возможность восстановить доступ к учетной записи
  - Пользователь должен иметь возможность сменить пароль учетной записи
  - Пользователь должен иметь возможность общаться в чате в лобби
  - Пользователь должен иметь возможность зайти и отредактировать свой профиль
  - Пользователь должен иметь возможность посмотреть и изменить настройки
  - Пользователь должен иметь возможность посмотреть рейтинг всех пользователей
  - Пользователь должен иметь возможность создавать задачи и просматривать уже созданные задачи
  - Пользователь должен иметь возможность просматривать и участвовать в турнирах, а также их создавать
  - Пользователь должен иметь возможность выйти из учетной записи
  - Пользователь должен иметь возможность перейти в сообщество codebattle на других площадках
  - Пользователь должен иметь возможность просматривать чужие игры
  - Пользователь должен иметь возможность сыграть пробную игру без авторизации
  - Пользователь должен иметь возможность авторизоваться через github и discord
  - Пользователь должен иметь возможность создавать игру с ботом
  - Пользователь должен иметь возможность создавать и пригласить другого игрока
  - Пользователь должен иметь возможность создавать игру, к которой может присоедениться любой игрок в лобби
  - Пользователь должен иметь возможность сменить язык программирования во время игры
non-funtional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - У пользователей в игре должно быть одинаковое время на решение задачи
  - У пользователя не должно быть доступа к консоли соперника во время игры
  - Игра должна закончится только если кто-то из игроков завершит задание или закончится время
  - Пользователь должен иметь возможность удалить свою учетную запись
  - Пользователь не может одновременно участвовать в нескольких играх